//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LichSuNhiemVu
    {
        public int LichSuID { get; set; }
        public Nullable<int> NhiemVuID { get; set; }
        public Nullable<int> NguoiThayDoiID { get; set; }
        public string MoTaThayDoi { get; set; }
        public Nullable<System.DateTime> NgayThayDoi { get; set; }
    }
}
