//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NganSach
    {
        public int NganSachID { get; set; }
        public Nullable<int> DuAnID { get; set; }
        public Nullable<decimal> SoTien { get; set; }
        public string MoTa { get; set; }
        public Nullable<System.DateTime> NgayCapNhat { get; set; }
    }
}
