//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanHoi
    {
        public int PhanHoiID { get; set; }
        public Nullable<int> DuAnID { get; set; }
        public Nullable<int> NguoiDungID { get; set; }
        public string NoiDungPhanHoi { get; set; }
        public Nullable<System.DateTime> NgayPhanHoi { get; set; }
    }
}
